#!/bin/bash

# put this script under /etc/hotplug.d/inface/
# when the interface "wlan0" is up, this script will run
# change "wlan0" to your needs
# chagne path to dtc-show-ip
# chagne meesage

# Huanle Zhang
# www.huanlezhang.com

[ ifup = "$ACTION" -a "$DEVICE" = wlan0 ] && {
	/bin/bash /usr/bin/dtc-show-ip.sh " " >> /root/log.txt 2>&1
}
